CustomHealthAPI.PersistentData.CharactersThatCantHaveRedHealth[PlayerType.PLAYER_BLUEBABY] = true
CustomHealthAPI.PersistentData.CharactersThatCantHaveRedHealth[PlayerType.PLAYER_BLACKJUDAS] = true
CustomHealthAPI.PersistentData.CharactersThatCantHaveRedHealth[PlayerType.PLAYER_JUDAS_B] = true
CustomHealthAPI.PersistentData.CharactersThatCantHaveRedHealth[PlayerType.PLAYER_BLUEBABY_B] = true
CustomHealthAPI.PersistentData.CharactersThatCantHaveRedHealth[PlayerType.PLAYER_THEFORGOTTEN_B] = true
CustomHealthAPI.PersistentData.CharactersThatCantHaveRedHealth[PlayerType.PLAYER_BETHANY_B] = true

CustomHealthAPI.PersistentData.CharactersThatConvertMaxHealth[PlayerType.PLAYER_BLUEBABY] = "SOUL_HEART"
CustomHealthAPI.PersistentData.CharactersThatConvertMaxHealth[PlayerType.PLAYER_BLACKJUDAS] = "BLACK_HEART"
CustomHealthAPI.PersistentData.CharactersThatConvertMaxHealth[PlayerType.PLAYER_JUDAS_B] = "BLACK_HEART"
CustomHealthAPI.PersistentData.CharactersThatConvertMaxHealth[PlayerType.PLAYER_BLUEBABY_B] = "SOUL_HEART"
CustomHealthAPI.PersistentData.CharactersThatConvertMaxHealth[PlayerType.PLAYER_THEFORGOTTEN_B] = "SOUL_HEART"
CustomHealthAPI.PersistentData.CharactersThatConvertMaxHealth[PlayerType.PLAYER_BETHANY_B] = "SOUL_HEART"
