CustomHealthAPI.Enums.HealthTypes = {
	RED = 0,
	SOUL = 1,
	CONTAINER = 2,
	OVERLAY = 3,
}

CustomHealthAPI.Enums.HealthKinds = {
	NONE = -1,
	HEART = 0,
	COIN = 1,
}

CustomHealthAPI.Enums.Callbacks = {
	ON_SAVE = 1,
	ON_LOAD = 2,
	PRE_ADD_HEALTH = 3,
	PRE_RENDER_HEART = 4,
	POST_RENDER_HP_BAR = 5,
	PRE_RENDER_HOLY_MANTLE = 6,
	POST_HEALTH_DAMAGED = 7,
	PRE_PLAYER_DAMAGE = 8,
	POST_PLAYER_DAMAGE = 9,
	POST_PLAYER_GENESIS = 10,
	POST_GENESIS = 11,
	PRE_ETERNAL_HEAL = 12,
	PRE_SPIRIT_SHACKLES_HEAL = 13,
	PRE_HEARTBREAK_HEAL = 13,
	PRE_RENDER_UNKNOWN_CURSE = 14,
	CAN_PICK_HEALTH = 15,
	POST_RESYNC_PLAYER = 16,
	POST_PLAYER_INITIALIZE = 17,
	POST_PLAYER_REVIVED = 18,
	GET_MAX_HP_CONVERSION = 19,
	PRE_HEALTH_DAMAGED = 20,
	PRE_BLOOD_OATH_DAMAGE = 21,
	PRE_GLASS_CANNON_HEAL = 22,
	PRE_NOKILL_HEAL = 23,
	POST_CHANGE_PLAYER_TYPE = 24,
}

CustomHealthAPI.Enums.PlayerSlot = {
	STRAWMAN = -2,
	ESAU = -1,
	PLAYER_ONE = 0,
	PLAYER_TWO = 1,
	PLAYER_THREE = 2,
	PLAYER_FOUR = 3,
}

CustomHealthAPI.Enums.CallbackPriorities = {
	LATE = 920,
}
