CustomHealthAPI.Enums.HealthTypes = {
	RED = 0,
	SOUL = 1,
	CONTAINER = 2,
	OVERLAY = 3,
}

CustomHealthAPI.Enums.HealthKinds = {
	NONE = -1,
	HEART = 0,
	COIN = 1,
}

CustomHealthAPI.Enums.Callbacks = {
	ON_SAVE = 1,
	ON_LOAD = 2,
	PRE_ADD_HEALTH = 3,
	PRE_RENDER_HEART = 4,
	POST_RENDER_HP_BAR = 5,
	PRE_RENDER_HOLY_MANTLE = 6,
	POST_HEALTH_DAMAGED = 7,
	PRE_PLAYER_DAMAGE = 8,
	POST_PLAYER_DAMAGE = 9,
	POST_PLAYER_GENESIS = 10,
	POST_GENESIS = 11,
	PRE_ETERNAL_HEAL = 12,
	PRE_SPIRIT_SHACKLES_HEAL = 13,
	PRE_RENDER_UNKNOWN_CURSE = 14,
	CAN_PICK_HEALTH = 15,
	POST_RESYNC_PLAYER = 16,
	POST_PLAYER_INITIALIZE = 17,
	POST_PLAYER_REVIVED = 18,
	GET_MAX_HP_CONVERSION = 19,
	PRE_HEALTH_DAMAGED = 20,
	PRE_BLOOD_OATH_DAMAGE = 21,
	PRE_GLASS_CANNON_HEAL = 22,
	PRE_NOKILL_HEAL = 23,
	POST_CHANGE_PLAYER_TYPE = 24,
	PRE_SUMPTORIUM_CLOT_SELECT = 25,
	PRE_SUMPTORIUM_CLOT_INIT = 26,
	POST_SUMPTORIUM_CLOT_INIT = 27,
	PRE_SUMPTORIUM_CLOT_ABSORB = 28,
	POST_SUMPTORIUM_CLOT_ABSORB = 29,
	POST_ADD_HEALTH = 30,
	POST_RENDER_HEART = 31,
	POST_RENDER_HOLY_MANTLE = 32,
	POST_RENDER_UNKNOWN_CURSE = 33,
	POST_UPDATE_HEALTH_STATE = 34,
	PRE_HEARTBREAK_HEAL = 35,
	GET_MAX_HP_CAP = 36,
	PRE_RENDER_LIVES = 37,
	POST_RENDER_LIVES = 38,
}

CustomHealthAPI.Enums.PlayerSlot = {
	STRAWMAN = -1,
	PLAYER_ONE = 0,
	PLAYER_TWO = 1,
	PLAYER_THREE = 2,
	PLAYER_FOUR = 3,
	ESAU = 4,
	PLAYER_ONE_ESAU = 4,
	PLAYER_TWO_ESAU = 5,
	PLAYER_THREE_ESAU = 6,
	PLAYER_FOUR_ESAU = 7,
}

CustomHealthAPI.Enums.CallbackPriorities = {
	FIRST = math.mininteger,
	EARLY = -920,
	LATE = 920,
}
